# =======================================================
# - 글로벌 셋팅
# =======================================================


---
# =======================================================
# - 로컬 환경 셋팅
# =======================================================
spring:
  profiles: local

feign:
  client:
    config:
      default:
        # 커넥션 타임아웃 : 3초
        connectTimeout: 3000
        # 리드 타임아웃 : 5초
        readTimeout: 5000
        # 로그 레벨 : 전
        loggerLevel: FULL
  biz:
    name: "bizFeignClient"
    url: "http://localhost:8082"

logging:
  level:
    com.kenny.demo.oslodemowithjavajpa.clientfeign.feign: ERROR
