# =======================================================
# - 글로벌 셋팅
# =======================================================


---
# =======================================================
# - 로컬 환경 셋팅
# =======================================================
spring:
  profiles: local

client:
  biz:
    name: "bizFeignClient"
    url: "http://localhost:8082"
