# =======================================================
# - 글로벌 셋팅
# =======================================================


---
# =======================================================
# - 로컬 환경 셋팅
# =======================================================
spring:
  profiles: local

client:
  feign:
    to_biz:
      url: localhost
      port: 8082

