# =======================================================
# - 글로벌 셋팅
# =======================================================

---
# =======================================================
# - 로컬 환경 셋팅
# =======================================================
spring:
  profiles: local
  # DataSouce 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/oslo_demo_postgresql
    username: develop
    password: 1qaz@WSX
    driver-class-name: org.postgresql.Driver
    # Hikari CP 설정
    hikari:
      # 디폴트 : 10
      maximum-pool-size: 50
      # 디폴트 : 180000( 30분 )
      max-lifetime: 180000
      # 디폴트 : 30000( 30초 )
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # JPA 설정
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true

# 로깅 레벨 설정 : yml --> logback
logging.level:
  org.hibernate: INFO


