# =======================================================
# - 글로벌 셋팅
# =======================================================
spring:
  application:
    name: oslo-demo-hub
  profiles:
    include:
      - client-feign

server:
  port: 8081

---
# =======================================================
# - 로컬 환경 셋팅
# =======================================================
spring:
  profiles: local
