# =======================================================
# - 글로벌 셋팅
# =======================================================
spring:
  application:
    name: oslo-demo-biz
  profiles:
    include:
      - db-redis
      - broker-kafka
server:
  port: 8082

---
# =======================================================
# - 로컬 환경 셋팅
# =======================================================
spring:
  profiles: local

