# =======================================================
# - 글로벌 셋팅
# =======================================================
spring:
  application:
    name: oslo-demo-biz
  profiles:
    include:
      - client-feign
      - db-postgresql
      - db-redis
      - broker-kafka
server:
  port: 8082

---
# =======================================================
# - 로컬 환경 셋팅
# =======================================================
spring:
  profiles: local

# 로깅 레벨 설정 : yml --> logback
logging.level:
  root: INFO
  com.kenny.demo.oslodemowithjavajpa: DEBUG