# =======================================================
# - 글로벌 셋팅
# =======================================================
spring:
  application:
    name: oslo-demo-consumer

server:
  port: 8083

---
# =======================================================
# - 로컬 환경 셋팅
# =======================================================
spring:
  profiles: local
