CREATE TABLESPACE DEV_SPACE DATAFILE 'dev_space.dat' SIZE 500M AUTOEXTEND ON NEXT 10M;
DEFINE NEW_USER = 'develop';
CREATE USER &NEW_USER IDENTIFIED BY "1qaz@WSX";
GRANT CONNECT, RESOURCE, CREATE JOB, CREATE VIEW, CREATE ANY CONTEXT TO &NEW_USER;
ALTER USER &NEW_USER QUOTA UNLIMITED ON USERS;
ALTER USER &NEW_USER DEFAULT TABLESPACE DEV_SPACE;

CREATE TABLE BOARD (
      IDX        NUMBER          NOT NULL PRIMARY KEY
    , NAME       VARCHAR2(50)    NOT NULL
    , EMAIL      VARCHAR2(50)    NOT NULL
    , PASSWD     VARCHAR2(50)    NOT NULL
    , CONTENT    VARCHAR2(1000)  NOT NULL
    , POST_DATE  DATE DEFAULT SYSDATE
);

COMMIT;